### ISSUE TITLE
Option not occuring in menu

### ISSUE THREAD

**Issue by orschiro** [dhwlm/delete-whitelines#2]
Hey @dhwlm 

Thanks so much! Exactly what I was looking for. 

however not working for me: https://youtu.be/zNKxOmfp3IY

Any insights?

Keyboard shortcut not working either. :-(

**Comment by dhwlm** [comment]
Have published new code. should work now. let me know if the issue persists.

**Comment by orschiro** [comment]
Cool, thank you, @dhwlm! :-)
