### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by dundunn** [dhwlm/delete-whitelines#3]
Calling "Delete Whitelines: Toggle" currently does nothing on my system. 

Atom-Version: 1.29.0
System: Windows 10 Pro

**Comment by codificandoCodigo** [comment]
Hi, i make a pull request with the fix.
please take a look at it.
Cheers.

**Comment by dhwlm** [comment]
I've merged @codificandoCodigo 's code. let me know if the issue persists. @codificandoCodigo thanks mate!
